name: middleware_flutter_opentelemetry
description: "A Flutter package for OpenTelemetry based on middleware_dart_opentelemetry"
version: 1.0.1
publisher: middleware.io
homepage: https://midlleware.io
repository: https://github.com/middleware-labs/flutter-sdk.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  middleware_dart_opentelemetry: ^1.0.4
  dartastic_opentelemetry_api: ^0.8.8
  http: ^1.6.0
  #TODO - need to manage go_router dependency versions and no-go-router implementation
  go_router: ^14.8.1
  meta: ^1.16.0
  uuid: ^4.5.1
  web: ^1.1.1
  archive: ^4.0.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  build_runner: ^2.4.15
